apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: de4s045bn-java-springboot
  janus-idp.io/tekton: de4s045bn-java-springboot
  backstage.io/kubernetes-id: de4s045bn-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: de4s045bn-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
